#!/bin/bash

echo Press 'y' to deploy $1

read -s -n 1 k <&1

if [[ $k != y ]] ; then
  printf "\nQuit\n"
else
  echo destroying $1
  REACT_APP_BUILD_DATE=$(date) REACT_APP_GIT_SHA=$(git rev-parse --short HEAD) BUILD_ENV=$1 ./node_modules/.bin/cdk destroy
fi
