name: 'CodeQL'

on:
  push:
    branches: [master]

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_args: '--require-approval never'
          actions_comment: true
          cdk_version: '2.9.0'
          working_dir: 'cdk'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
          AWS_CERT_ARN: ${{ secrets.AWS_CERT_ARN }}
          BUILD_ENV: ${{ secrets.BUILD_ENV }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          CDK_DEFAULT_REGION: 'us-east-1'
          DOMAIN_NAME: 'u25dev.com'
          REACT_APP_GIT_SHA: ${{ github.sha }}
          REACT_APP_BUILD_DATE: ${{ steps.date.outputs.date }}
